# Generated by Django 3.0.3 on 2020-02-06 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('contact_no', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PROFILE',
                'db_table': 'profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('contact_no', models.IntegerField()),
                ('facility', models.CharField(max_length=255)),
                ('furniture', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=255)),
                ('food', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=255)),
                ('rent', models.IntegerField()),
                ('type', models.CharField(choices=[('flat', 'FLAT'), ('pg', 'PG'), ('room', 'ROOM')], default=None, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PG',
                'db_table': 'pg',
                'managed': True,
            },
        ),
    ]
